#!/usr/bin/env bash

###############################################
# Installing iva
#
# by Tiziano Gallo Cassarino, 2015 
#

NAME=${NAME:-iva}
VERSION=${VERSION:-1.0.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION}

# Note, you need the following packages loaded to build this:
dirname=$(dirname $0 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/require_inc.sh
require compilers/gnu
require python3/recommended
require kmc
require mummer
require trimmomatic
require samtools/1.2
require smalt

pip3 install --install-option="--prefix=$INSTALL_PREFIX" iva==$VERSION

# need to change the #! to have python3 instead of 1435743341-3 from the bundle when pip was used
cd $INSTALL_PREFIX/bin
sed -i.bak '1s|^#!.*|#!/usr/bin/env python3|' *
