#!/usr/bin/env bash

###############################################
# Installing iva
#
# by Tiziano Gallo Cassarino 2015 
#

NAME=${NAME:-iva}
VERSION=${VERSION:-1.0.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/${NAME}/$VERSION}

# Note, you need the following packages loaded to build this:
source /shared/ucl/apps/modules/3.2.6/Modules/3.2.6/init/bash
export MODULEPATH=$MODULESDIR_FINAL:$MODULEPATH
module load compilers/gnu/4.9.2
module load bundles/python3/recommended
module load kmc
module load mummer
module load trimmomatic
module load samtools/1.2
module load bambamc
module load smalt

pip3 install --install-option="--prefix=$INSTALL_PREFIX" iva==$VERSION

# need to change the #! to have python3 instead of 1435743341-3 from the bundle when pip was used
cd $INSTALL_PREFIX/bin
sed -i.bak '1s|^#!.*|#!/usr/bin/env python3|' *
